---
title: "Activities from Week 10, Lecture 1: Data Ethics"
subtitle: "SDS 192: Introduction to Data Science"
author: "Camilla Rosour"
---

## Introduction

We've discussed some ideas regarding data ethics. With those around you, you will discuss your thoughts on the video and answer questions regarding two different articles.

## Carissa Véliz: How privacy can save your life

You've just watched a TEDTalk from Carissa Véliz about how data privacy should be used to protect your livelihood. You can access the video for reference [here](https://www.youtube.com/watch?v=xSPRouBvgFE).

After talking to others about the video, answer the following questions below:

::: callout-important
###### Q1

What are some important ideas that Carissa Véliz talked about in the video? What are your thoughts to some of the examples she used and her perspective?

-   what kinds of data should be collected?
-   the concept of ownership and how it differs between analog and digital thing. i didn't like the example of the paper book vs the digital book because i thought it fell flat and didn't get to the root of privacy issues. i understand what she meant though.
:::

## Your data is diminishing your freedom

Read the New York Times article "Your Data is Diminishing Your Freedom" at the following link [here](https://www.nytimes.com/interactive/2023/03/20/magazine/colin-koopman-interview.html). After discussing your thoughts on the piece, answer the following questions:

::: callout-important
###### Q2

What does it mean that "we have become our own data?" How does that sentiment affect your personal decision-making, and how we define ourselves?

We become our own data because it has a direct impact on our lives. We must "tend" to our data like the example with credit scores. The sentiment affects your decision making because it effects the way you are percieved, your life chances, and how you inevitably live your life. The kind of demographic data that is taken becomes the way people define themselves and others, becoming more important than "real life."
:::

::: callout-important
###### Q3

Using the article as support, what are some concerns you personally have about the use of your data?

I'm concerned about the use of my data to train AI models. In the article, Marchese talks about facial-recognition software specifically and how they tend to misclassify black faces. There are biases built into the systems, and its an invasion of people privacy to use their likeness to train these models.
:::

## Federal Data Strategy

The U.S. Government has a Federal Data Strategy with the hopes of defining how to use data to serve the public and steward resources while "protecting security, privacy, and confidentiality."

You will read page 4 of the Data Ethics Framework based on the strategy [here](https://resources.data.gov/assets/documents/fds-data-ethics-framework.pdf). After discussing your thoughts on the piece, answer the following questions:

::: callout-important
###### Q4

Discuss examples about how a government (or smaller body) could execute a data ethics tenet of your choice.

2, Respect the public, individuals, and communities
- value impact over intent
- have representatives from a variety of groups to avoid biases

:::

## Turn-in

Save the .qmd file inside your activities repository. Please stage, commit, and push to GitHub.
